"""
- docstring is generated by AI and checked over 

Validate expected pipeline outputs in a Butler repository and
generate ingestion tables.

This script compares a list of expected dataset types and data IDs
(defined in ``output_types.txt`` and corresponding ``*_outlist.pkl.gz``
files) against the contents of a specified Butler output collection.
For each expected data ID, it checks whether the dataset exists in
the repository.

If any datasets are missing, the script exits with status code 1.
If all expected datasets are found, it generates CSV ingestion tables
mapping output file paths to their corresponding data IDs and exits
with status code 0.

Command-line arguments
----------------------
1. Butler repository path
2. Transfer directory (containing expected output lists)
3. Output collection name
4. Final output path for constructing ingestion file paths
"""



import numpy as np
import lsst
from lsst import daf
from lsst.daf.butler import Butler
import gzip, pickle
import sys
from pathlib import Path
import csv


butler = Butler(sys.argv[1], writeable=False)
transfer_path = sys.argv[2]
outcoll = sys.argv[3]
relpath = sys.argv[1]
final_path = sys.argv[4]

output_types =  np.atleast_1d(np.loadtxt(transfer_path+'/output_types.txt',dtype=str)).tolist()
print("expected outputs are ", output_types)

rows={}
missing_bool=False
missing_tot = 0

for outs in output_types:
    rows[outs]=[]
    INP = transfer_path + '/' +outs+"_outlist.pkl.gz"
    found = 0
    missing = 0
    with gzip.open(INP, "rb") as f:
        dataids = pickle.load(f)
    for dataId in dataids:
        refs = list(
            butler.registry.queryDatasets(
                outs,
                collections=[outcoll],
                dataId = dataId,
            )
        )
        if refs:
            found +=1
            for ref in refs:
                for uri in butler.getURIs(ref):
                    if isinstance(uri, dict):
                        continue
                    scheme = getattr(uri, "scheme", None)
                    dataid = dict(ref.dataId.mapping)
                    src_path = Path(uri.ospath)
                    try:
                        rel = src_path.relative_to(relpath)
                        outpath = Path(final_path) / rel
                    except ValueError:
                        outpath = Path(final_path) / src_path.name
                    rows[outs].append({"path": str(outpath), **dataid})
        else:
            missing+=1
    missing_tot += missing

    if missing_tot!=0:
        missing_bool=True

if missing_bool:
    print("Found ", found, " refs and missing ", missing, " refs.")
    sys.exit(1)
else:
    print("Found ", found, " refs and missing ", missing, " refs.")
    Path(transfer_path, "ingestion_files").mkdir(parents=True, exist_ok=True)
    for key in rows.keys():
        table_csv = transfer_path + '/ingestion_files/' + key+"_ingest_table_outputs.csv"
        with open(table_csv, "w", newline="") as f:
            fieldnames = ["path"] + sorted({k for r in rows[key] for k in r.keys() if k != "path"})
            w = csv.DictWriter(f, fieldnames=fieldnames)
            w.writeheader()
            w.writerows(rows[key])

    sys.exit(0)

