# CI workflow to publish the docker image for the DESC Rubin Globus
# Compute project

name: Publish DESC Rubin Globus Compute Docker image

on:
  # Can be triggered to run manually.
  workflow_dispatch:

# Login to dockerhub, build, and publish.
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set current date as env variable
        run: echo "NOW=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: jchiang87/rubin-globus-compute:w_2025_17
          build-args: BUILD_DATE=${{ env.NOW }}
